# Generated by Django 2.2 on 2021-04-29 09:28

from django.db import migrations, models
import django.db.models.deletion
import factory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=factory.models.create_invoice_number, max_length=12)),
                ('date_of_issue', models.DateField(auto_now=True)),
                ('time_of_issue', models.TimeField(auto_now=True)),
                ('payment_due', models.DateField()),
                ('date_of_payment', models.DateField(blank=True, null=True)),
                ('time_of_payment', models.TimeField(blank=True, null=True)),
                ('to_be_delivered', models.BooleanField(default=False)),
                ('completed', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='factory.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('about', models.TextField(blank=True, null=True)),
                ('available_stock', models.IntegerField()),
                ('measurement', models.CharField(choices=[('bag', 'Bag'), ('box', 'Carton / Box')], default='bag', max_length=30)),
                ('weight_in_kg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(default=factory.models.create_staff_id, max_length=30)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('date_of_employment', models.DateField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField()),
                ('time_received', models.TimeField()),
                ('reveived_from', models.CharField(blank=True, max_length=100, null=True)),
                ('shipment_id', models.CharField(default=factory.models.stamp, max_length=12)),
                ('items', models.ManyToManyField(blank=True, related_name='received', to='factory.Resource')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory.Shipment'),
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_production', models.DateField()),
                ('time_of_production', models.TimeField()),
                ('output', models.IntegerField()),
                ('production_id', models.CharField(default=factory.models.stamp, max_length=20, unique_for_date='date_of_production')),
                ('ingredients', models.ManyToManyField(blank=True, related_name='used', to='factory.Ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='factory.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='factory.Invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='factory.Product')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items', to='factory.Order_Item'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.Production'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.Resource'),
        ),
    ]
