# Generated by Django 2.2 on 2021-04-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='reveived_from',
            new_name='received_from',
        ),
    ]
