# Generated by Django 2.2 on 2021-04-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_auto_20210429_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=200)),
                ('verbose_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='level',
        ),
        migrations.AddField(
            model_name='worker',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='role',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='factory.Staff_Permission'),
        ),
    ]
