# Generated by Django 2.2 on 2021-04-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_auto_20210429_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product-images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='online_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_due',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
