# Generated by Django 2.2 on 2021-04-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_auto_20210429_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_cost',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement',
            field=models.CharField(choices=[('bag', 'Bag'), ('box', 'Box / Carton'), ('crate', 'Crate')], default='bag', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='online_sale',
            field=models.BooleanField(default=True),
        ),
    ]
