# Generated by Django 2.2 on 2021-05-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_auto_20210430_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='output',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
