# Generated by Django 2.2 on 2021-05-01 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_auto_20210501_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='entry',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='unit',
            field=models.CharField(choices=[('bag', 'Bag'), ('box', 'Box / Carton'), ('crate', 'Crate')], default='bag', max_length=30),
        ),
    ]
