# Generated by Django 2.2 on 2021-05-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0009_auto_20210501_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='entry',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
