# Generated by Django 2.2 on 2021-05-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0010_auto_20210501_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='weight_in_kg',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
